name: Auto IP Collect
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 8
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requirements
        run: pip install requests

      - name: Run IP Script
        run: python ip_collect.py

      - name: Commit & Push Fix 403
        run: |
          git config --global user.name "rjdsq"
          git config --global user.email "你的邮箱@qq.com"
          git add max.txt
          git commit -m "auto refresh max.txt"
          git push origin main --force
